-- 移动储能系统业务表
-- 基于 RuoYi-Vue-Pro，模块名：yudao-module-energy

CREATE TABLE IF NOT EXISTS energy_customer (
  id BIGINT NOT NULL COMMENT '客户编号',
  name VARCHAR(128) NOT NULL COMMENT '客户名称',
  contact_name VARCHAR(64) NULL COMMENT '联系人',
  contact_mobile VARCHAR(32) NULL COMMENT '联系电话',
  region VARCHAR(64) NULL COMMENT '区域',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 启用，1 停用',
  remark VARCHAR(512) NULL COMMENT '备注',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  KEY idx_energy_customer_status (status),
  KEY idx_energy_customer_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能客户';

CREATE TABLE IF NOT EXISTS energy_project (
  id BIGINT NOT NULL COMMENT '项目编号',
  customer_id BIGINT NOT NULL COMMENT '客户编号',
  name VARCHAR(128) NOT NULL COMMENT '项目名称',
  code VARCHAR(64) NOT NULL COMMENT '项目编码',
  address VARCHAR(255) NULL COMMENT '地址',
  latitude DECIMAL(10,6) NULL COMMENT '纬度',
  longitude DECIMAL(10,6) NULL COMMENT '经度',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 启用，1 停用',
  remark VARCHAR(512) NULL COMMENT '备注',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  UNIQUE KEY uk_energy_project_code (code, deleted),
  KEY idx_energy_project_customer_id (customer_id),
  KEY idx_energy_project_status (status),
  KEY idx_energy_project_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能项目/场站';

CREATE TABLE IF NOT EXISTS energy_device (
  id BIGINT NOT NULL COMMENT '设备编号',
  device_no VARCHAR(64) NOT NULL COMMENT '设备编码',
  device_name VARCHAR(128) NOT NULL COMMENT '设备名称',
  device_type TINYINT NOT NULL COMMENT '设备类型',
  gateway_sn VARCHAR(64) NULL COMMENT '网关序列号',
  meter_sn VARCHAR(64) NULL COMMENT '电表序列号',
  meter_no VARCHAR(128) NULL COMMENT '仪表编号',
  customer_id BIGINT NULL COMMENT '客户编号',
  project_id BIGINT NULL COMMENT '项目编号',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '设备状态：0 在线，1 离线，2 故障，3 维护',
  run_mode TINYINT NULL COMMENT '运行模式：0 充电，1 放电，2 待机，3 故障',
  latitude DECIMAL(10,6) NULL COMMENT '纬度',
  longitude DECIMAL(10,6) NULL COMMENT '经度',
  last_soc DECIMAL(6,2) NULL COMMENT '最新 SOC',
  last_soh DECIMAL(6,2) NULL COMMENT '最新 SOH',
  last_power DECIMAL(12,3) NULL COMMENT '最新功率',
  last_voltage DECIMAL(12,3) NULL COMMENT '最新电压',
  last_current DECIMAL(12,3) NULL COMMENT '最新电流',
  last_temp DECIMAL(8,2) NULL COMMENT '最新温度',
  last_reading_time DATETIME NULL COMMENT '最新采集时间',
  remark VARCHAR(512) NULL COMMENT '备注',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  UNIQUE KEY uk_energy_device_no (device_no, deleted),
  UNIQUE KEY uk_energy_device_meter_no (meter_no, deleted),
  KEY idx_energy_device_customer_id (customer_id),
  KEY idx_energy_device_project_id (project_id),
  KEY idx_energy_device_status (status),
  KEY idx_energy_device_gateway_sn (gateway_sn),
  KEY idx_energy_device_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能设备';

CREATE TABLE IF NOT EXISTS energy_vehicle (
  id BIGINT NOT NULL COMMENT '车辆编号',
  vehicle_no VARCHAR(64) NOT NULL COMMENT '车辆编码',
  plate_no VARCHAR(32) NULL COMMENT '车牌号',
  qr_code VARCHAR(128) NOT NULL COMMENT '车辆二维码编码',
  device_id BIGINT NOT NULL COMMENT '绑定设备编号',
  customer_id BIGINT NULL COMMENT '客户编号',
  project_id BIGINT NULL COMMENT '项目编号',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 启用，1 停用',
  remark VARCHAR(512) NULL COMMENT '备注',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  UNIQUE KEY uk_energy_vehicle_no (vehicle_no, deleted),
  UNIQUE KEY uk_energy_vehicle_qr_code (qr_code, deleted),
  KEY idx_energy_vehicle_plate_no (plate_no),
  KEY idx_energy_vehicle_device_id (device_id),
  KEY idx_energy_vehicle_customer_id (customer_id),
  KEY idx_energy_vehicle_project_id (project_id),
  KEY idx_energy_vehicle_status (status),
  KEY idx_energy_vehicle_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能车辆绑定';

INSERT INTO energy_vehicle (
  id, vehicle_no, plate_no, qr_code, device_id, customer_id, project_id, status, remark, creator, updater, tenant_id
) VALUES (
  202606090001, 'VEH-DEMO-001', '测试A001', 'QR-VEH-DEMO-001', 202605310003, NULL, NULL, 0, 'Local demo vehicle bound to test device', 'system', 'system', 1
) ON DUPLICATE KEY UPDATE device_id = VALUES(device_id), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS energy_app_user (
  id BIGINT NOT NULL COMMENT 'App user id',
  username VARCHAR(64) NOT NULL COMMENT 'Username',
  password VARCHAR(128) NOT NULL COMMENT 'BCrypt password',
  nickname VARCHAR(64) NOT NULL COMMENT 'Nickname',
  mobile VARCHAR(32) NULL COMMENT 'Mobile',
  card_no VARCHAR(64) NULL COMMENT '刷卡卡号',
  mini_admin_enabled BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否开放小程序管理端权限',
  status TINYINT NOT NULL DEFAULT 0 COMMENT 'Status: 0 enabled, 1 disabled',
  login_ip VARCHAR(50) NULL COMMENT 'Last login IP',
  login_date DATETIME NULL COMMENT 'Last login time',
  remark VARCHAR(512) NULL COMMENT 'Remark',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT 'Creator',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT 'Updater',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT 'Deleted flag',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT 'Tenant id',
  PRIMARY KEY (id),
  UNIQUE KEY uk_energy_app_user_username (username, deleted),
  UNIQUE KEY uk_energy_app_user_card_no (card_no, deleted),
  KEY idx_energy_app_user_mobile (mobile),
  KEY idx_energy_app_user_mini_admin (mini_admin_enabled),
  KEY idx_energy_app_user_status (status),
  KEY idx_energy_app_user_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Energy App user';

CREATE TABLE IF NOT EXISTS energy_customer_account (
  id BIGINT NOT NULL COMMENT '客户老板账号编号',
  customer_id BIGINT NOT NULL COMMENT '客户编号',
  system_user_id BIGINT NOT NULL COMMENT '后台登录用户编号',
  role_id BIGINT NOT NULL COMMENT '专属角色编号',
  username VARCHAR(30) NOT NULL COMMENT '登录账号',
  nickname VARCHAR(64) NOT NULL COMMENT '账号名称',
  mobile VARCHAR(32) NULL COMMENT '手机号',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 启用，1 停用',
  menu_ids VARCHAR(1024) NULL COMMENT '开放板块菜单编号，逗号分隔',
  remark VARCHAR(512) NULL COMMENT '备注',
  creator VARCHAR(64) NULL DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) NULL DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT(1) NOT NULL DEFAULT b'0',
  tenant_id BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_energy_customer_account_username (username, tenant_id, deleted),
  KEY idx_energy_customer_account_customer_id (customer_id),
  KEY idx_energy_customer_account_system_user_id (system_user_id),
  KEY idx_energy_customer_account_role_id (role_id),
  KEY idx_energy_customer_account_status (status),
  KEY idx_energy_customer_account_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能客户老板网页账号';

CREATE TABLE IF NOT EXISTS energy_account_event (
  id BIGINT NOT NULL COMMENT 'Account event id',
  event_scene VARCHAR(32) NOT NULL COMMENT 'Event scene: VERIFY/DISCHARGE',
  auth_type VARCHAR(16) NOT NULL COMMENT 'Auth type: WECHAT/CARD',
  scan_text VARCHAR(512) NULL COMMENT 'Scanned device QR content',
  card_no VARCHAR(64) NULL COMMENT 'Card number',
  account_known BIT(1) NOT NULL DEFAULT b'0' COMMENT 'Whether account is known and authorized',
  account_id BIGINT NULL COMMENT 'App user id',
  account_name VARCHAR(64) NULL COMMENT 'App user name',
  account_mobile VARCHAR(32) NULL COMMENT 'App user mobile',
  device_id BIGINT NULL COMMENT 'Device id',
  device_no VARCHAR(64) NULL COMMENT 'Device number',
  device_name VARCHAR(128) NULL COMMENT 'Device name',
  meter_no VARCHAR(128) NULL COMMENT 'Meter number',
  gateway_sn VARCHAR(128) NULL COMMENT 'Gateway serial number',
  meter_sn VARCHAR(128) NULL COMMENT 'Meter serial number',
  customer_id BIGINT NULL COMMENT 'Customer id',
  project_id BIGINT NULL COMMENT 'Project id',
  result_message VARCHAR(256) NULL COMMENT 'Result message',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT 'Creator',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT 'Updater',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT 'Deleted flag',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT 'Tenant id',
  PRIMARY KEY (id),
  KEY idx_energy_account_event_device (device_id),
  KEY idx_energy_account_event_account (account_id),
  KEY idx_energy_account_event_auth (auth_type, account_known),
  KEY idx_energy_account_event_create_time (create_time),
  KEY idx_energy_account_event_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Energy account scan/card event';

CREATE TABLE IF NOT EXISTS energy_user_scope (
  id BIGINT NOT NULL COMMENT '用户授权范围编号',
  user_id BIGINT NOT NULL COMMENT '用户编号',
  user_type TINYINT NOT NULL COMMENT '用户类型：1 会员/App，2 管理员',
  customer_id BIGINT NULL COMMENT '授权客户编号',
  project_id BIGINT NULL COMMENT '授权项目编号',
  device_id BIGINT NULL COMMENT '授权设备编号',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 启用，1 停用',
  remark VARCHAR(512) NULL COMMENT '备注',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  KEY idx_energy_user_scope_user (user_type, user_id, status),
  KEY idx_energy_user_scope_customer_id (customer_id),
  KEY idx_energy_user_scope_project_id (project_id),
  KEY idx_energy_user_scope_device_id (device_id),
  KEY idx_energy_user_scope_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能用户授权范围';

CREATE TABLE IF NOT EXISTS energy_telemetry (
  id BIGINT NOT NULL COMMENT '采集数据编号',
  device_id BIGINT NOT NULL COMMENT '设备编号',
  gateway_sn VARCHAR(64) NULL COMMENT '网关序列号',
  meter_sn VARCHAR(64) NULL COMMENT '网关下仪表序列号',
  meter_no VARCHAR(128) NULL COMMENT '仪表编号',
  collect_time DATETIME NOT NULL COMMENT '采集时间',
  timestamp BIGINT NULL COMMENT 'Unix 时间戳',
  source VARCHAR(32) NULL COMMENT '数据类型：REALTIME/HISTORY',
  state VARCHAR(32) NULL COMMENT '仪表状态：ONLINE/OFFLINE',
  pa DECIMAL(12,3) NULL COMMENT 'A 相有功功率',
  pb DECIMAL(12,3) NULL COMMENT 'B 相有功功率',
  pc DECIMAL(12,3) NULL COMMENT 'C 相有功功率',
  ua DECIMAL(12,3) NULL COMMENT 'A 相电压',
  ub DECIMAL(12,3) NULL COMMENT 'B 相电压',
  uc DECIMAL(12,3) NULL COMMENT 'C 相电压',
  ia DECIMAL(12,3) NULL COMMENT 'A 相电流',
  ib DECIMAL(12,3) NULL COMMENT 'B 相电流',
  ic DECIMAL(12,3) NULL COMMENT 'C 相电流',
  p DECIMAL(12,3) NULL COMMENT '有功功率',
  q DECIMAL(12,3) NULL COMMENT '无功功率',
  pf DECIMAL(12,3) NULL COMMENT '功率因数',
  epi DECIMAL(14,3) NULL COMMENT '正向有功电能',
  epe DECIMAL(14,3) NULL COMMENT '反向有功电能',
  soc DECIMAL(6,2) NULL COMMENT 'SOC',
  soh DECIMAL(6,2) NULL COMMENT 'SOH',
  batt_voltage DECIMAL(12,3) NULL COMMENT '电池电压',
  batt_current DECIMAL(12,3) NULL COMMENT '电池电流',
  batt_temp DECIMAL(8,2) NULL COMMENT '电池温度',
  run_mode TINYINT NULL COMMENT '运行模式',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  KEY idx_energy_telemetry_device_time (device_id, collect_time),
  KEY idx_energy_telemetry_gateway_time (gateway_sn, collect_time),
  KEY idx_energy_telemetry_meter_time (meter_no, collect_time),
  KEY idx_energy_telemetry_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能采集明细';

CREATE TABLE IF NOT EXISTS energy_alarm (
  id BIGINT NOT NULL COMMENT '告警编号',
  alarm_no VARCHAR(64) NOT NULL COMMENT '告警业务编号',
  device_id BIGINT NOT NULL COMMENT '设备编号',
  code VARCHAR(64) NOT NULL COMMENT '告警代码',
  level TINYINT NOT NULL COMMENT '告警等级',
  title VARCHAR(128) NOT NULL COMMENT '告警标题',
  content VARCHAR(1024) NULL COMMENT '告警内容',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 未确认，1 已确认，2 已关闭',
  occur_time DATETIME NOT NULL COMMENT '发生时间',
  ack_user_id BIGINT NULL COMMENT '确认人',
  ack_time DATETIME NULL COMMENT '确认时间',
  close_time DATETIME NULL COMMENT '关闭时间',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  UNIQUE KEY uk_energy_alarm_no (alarm_no, deleted),
  KEY idx_energy_alarm_device_id (device_id),
  KEY idx_energy_alarm_level (level),
  KEY idx_energy_alarm_status (status),
  KEY idx_energy_alarm_occur_time (occur_time),
  KEY idx_energy_alarm_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能告警';

CREATE TABLE IF NOT EXISTS energy_alarm_handle_record (
  id BIGINT NOT NULL COMMENT '告警处理记录编号',
  alarm_id BIGINT NOT NULL COMMENT '告警编号',
  action VARCHAR(32) NOT NULL COMMENT '处理动作：ack/close',
  remark VARCHAR(1024) NULL COMMENT '处理备注',
  operator_user_id BIGINT NULL COMMENT '操作人',
  operate_time DATETIME NOT NULL COMMENT '操作时间',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  KEY idx_energy_alarm_handle_alarm_id (alarm_id),
  KEY idx_energy_alarm_handle_action (action),
  KEY idx_energy_alarm_handle_operate_time (operate_time),
  KEY idx_energy_alarm_handle_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能告警处理记录';

CREATE TABLE IF NOT EXISTS energy_pricing_rule (
  id BIGINT NOT NULL COMMENT '计费规则编号',
  customer_id BIGINT NULL COMMENT '客户编号',
  project_id BIGINT NULL COMMENT '项目编号',
  device_id BIGINT NULL COMMENT '设备编号',
  time_rate DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '时间单价',
  energy_rate DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '电量单价',
  effective_start DATETIME NOT NULL COMMENT '生效开始时间',
  effective_end DATETIME NULL COMMENT '生效结束时间',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 启用，1 停用',
  remark VARCHAR(512) NULL COMMENT '备注',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  KEY idx_energy_pricing_customer_id (customer_id),
  KEY idx_energy_pricing_project_id (project_id),
  KEY idx_energy_pricing_device_id (device_id),
  KEY idx_energy_pricing_status (status),
  KEY idx_energy_pricing_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能计费规则';

CREATE TABLE IF NOT EXISTS energy_charge_session (
  id BIGINT NOT NULL COMMENT '充放电会话编号',
  session_no VARCHAR(64) NOT NULL COMMENT '会话业务编号',
  device_id BIGINT NOT NULL COMMENT '设备编号',
  customer_id BIGINT NOT NULL COMMENT '客户编号',
  pricing_rule_id BIGINT NULL COMMENT '计费规则编号',
  session_type TINYINT NOT NULL COMMENT '会话类型：0 充电，1 放电',
  start_time DATETIME NOT NULL COMMENT '开始时间',
  end_time DATETIME NULL COMMENT '结束时间',
  start_energy DECIMAL(14,3) NULL COMMENT '开始电量读数',
  end_energy DECIMAL(14,3) NULL COMMENT '结束电量读数',
  total_energy DECIMAL(14,3) NULL COMMENT '总电量',
  duration_minutes INT NULL COMMENT '时长分钟',
  energy_fee DECIMAL(12,2) NULL COMMENT '电量费用',
  time_fee DECIMAL(12,2) NULL COMMENT '时间费用',
  total_fee DECIMAL(12,2) NULL COMMENT '总费用',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 进行中，1 已结束，2 异常',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  UNIQUE KEY uk_energy_charge_session_no (session_no, deleted),
  KEY idx_energy_charge_session_device_id (device_id),
  KEY idx_energy_charge_session_customer_id (customer_id),
  KEY idx_energy_charge_session_start_time (start_time),
  KEY idx_energy_charge_session_status (status),
  KEY idx_energy_charge_session_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能充放电会话';

CREATE TABLE IF NOT EXISTS energy_dispatch_task (
  id BIGINT NOT NULL COMMENT '调度任务编号',
  task_no VARCHAR(64) NOT NULL COMMENT '任务业务编号',
  device_id BIGINT NOT NULL COMMENT '设备编号',
  task_type TINYINT NOT NULL COMMENT '任务类型',
  target_power DECIMAL(12,3) NULL COMMENT '目标功率',
  target_soc DECIMAL(6,2) NULL COMMENT '目标 SOC',
  start_time DATETIME NULL COMMENT '计划开始时间',
  end_time DATETIME NULL COMMENT '计划结束时间',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 待下发，1 执行中，2 成功，3 失败，4 取消',
  command_payload VARCHAR(2048) NULL COMMENT '指令内容',
  result_msg VARCHAR(1024) NULL COMMENT '执行结果',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  UNIQUE KEY uk_energy_dispatch_task_no (task_no, deleted),
  KEY idx_energy_dispatch_task_device_id (device_id),
  KEY idx_energy_dispatch_task_status (status),
  KEY idx_energy_dispatch_task_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能调度任务';

CREATE TABLE IF NOT EXISTS energy_eiot_sync_log (
  id BIGINT NOT NULL COMMENT '同步日志编号',
  sync_type VARCHAR(32) NOT NULL COMMENT '同步类型：realtime/alarm',
  request_id VARCHAR(64) NULL COMMENT '请求编号',
  gateway_sn VARCHAR(64) NULL COMMENT '网关序列号',
  meter_sn VARCHAR(64) NULL COMMENT '电表序列号',
  payload_url VARCHAR(512) NULL COMMENT '原始报文归档地址',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 成功，1 失败',
  error_msg VARCHAR(1024) NULL COMMENT '错误信息',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  KEY idx_energy_eiot_log_request_id (request_id),
  KEY idx_energy_eiot_log_sync_type (sync_type),
  KEY idx_energy_eiot_log_create_time (create_time),
  KEY idx_energy_eiot_log_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能 EIOT 同步日志';

CREATE TABLE IF NOT EXISTS energy_device_control_log (
  id BIGINT NOT NULL COMMENT '操控日志编号',
  device_id BIGINT NOT NULL COMMENT '设备编号',
  device_no VARCHAR(64) NULL COMMENT '设备编码',
  gateway_sn VARCHAR(64) NULL COMMENT '网关序列号',
  meter_sn VARCHAR(64) NULL COMMENT '电表序列号',
  meter_no VARCHAR(128) NULL COMMENT '仪表编号',
  method VARCHAR(32) NOT NULL COMMENT '控制方法：SWITCH/REFRESH',
  value VARCHAR(2048) NULL COMMENT '控制参数',
  request_payload VARCHAR(4096) NULL COMMENT 'EIOT 请求体',
  response_payload VARCHAR(4096) NULL COMMENT 'EIOT 响应体',
  eiot_code VARCHAR(64) NULL COMMENT 'EIOT 返回码',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 成功，1 失败',
  error_msg VARCHAR(1024) NULL COMMENT '错误信息',
  operator_user_id BIGINT NULL COMMENT '操作人',
  operate_time DATETIME NOT NULL COMMENT '操作时间',
  creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (id),
  KEY idx_energy_control_log_device_time (device_id, operate_time),
  KEY idx_energy_control_log_gateway_meter (gateway_sn, meter_sn),
  KEY idx_energy_control_log_status (status),
  KEY idx_energy_control_log_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动储能设备操控日志';
